teams = {
    "Hawks": "#TrueToAtlanta",
    "Celtics": "#BleedGreen",
    "Nets": "#NetsWorld",
    "Hornets": "#AllFly",
    "Bulls": "#BullsNation",
    "Cavaliers": "#BeTheFight",
    "Mavericks": "#MFFL",
    "Nuggets": "#MileHighBasketball",
    "Pistons": "#Pistons",
    "Warriors": "#DubNation",
    "Rockets": "#Rockets",
    "Pacers": "#GoldBlooded",
    "Clippers": "#ClipperNation",
    "Lakers": "#LakeShow",
    "Grizzlies": "#GrindCity",
    "Heat": "#HEATCulture",
    "Bucks": "#FearTheDeer",
    "Timberwolves": "#WolvesBack",
    "Pelicans": "#WBD",
    "Knicks": "#NewYorkForever",
    "Thunder": "#ThunderUp",
    "Magic": "#MagicTogether",
    "76ers": "#PhilaUnite",
    "Suns": "#ValleyProud",
    "Trail Blazers": "#RipCity",
    "Kings": "#SacramentoProud",
    "Spurs": "#PorVida",
    "Raptors": "#WeTheNorth",
    "Jazz": "#TakeNote",
    "Wizards": "#DCAboveAll",
}
